<?php

namespace Database\Seeders;

use App\Models\cat_usos;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CatUsosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events=[
            ['cuso_catego'=>'Alimento humano',                 'cuso_uso'=>'Bebidas',                                         'cuso_describe'=>'Bebidas (alcohólicas y no alcohólicas, estimulantes, calmantes, zumos, infusiones no medicinales, etc.).'],
            ['cuso_catego'=>'Alimento humano',                 'cuso_uso'=>'Condimentos, hierbas, especias',                  'cuso_describe'=>'Condimentos, hierbas, especias (condimentos, salsas, salsas, chutneys, guarniciones, pimienta, condimentos, etc.)'],
            ['cuso_catego'=>'Alimento humano',                 'cuso_uso'=>'Verduras y frutas',                               'cuso_describe'=>'Verduras y frutas (encurtidos, ensaladas, mermeladas y jaleas, frutas de postre, etc.)'],
            ['cuso_catego'=>'Alimento humano',                 'cuso_uso'=>'Legumbres',                                       'cuso_describe'=>'Legumbres (lentejas, soja, guisantes, garbanzos, cacahuetes, judías, dals, etc.)'],
            ['cuso_catego'=>'Alimento humano',                 'cuso_uso'=>'Granos, arroz',                                   'cuso_describe'=>'Granos, arroz (avena, cereales, panes, pasteles, arroz, quinua, cebada, etc.)'],
            ['cuso_catego'=>'Alimento humano',                 'cuso_uso'=>'Carbohidratos de raíces y tubérculos',            'cuso_describe'=>'Carbohidratos de raíces y tubérculos (papas, chayotextle, ñame, yuca, raíz de taro, cocoyam, achira, etc.)'],
            ['cuso_catego'=>'Alimento humano',                 'cuso_uso'=>'Frutos secos',                                    'cuso_describe'=>'Frutos secos (bellotas, almendras, nueces de vela, anacardos, castañas, avellanas, nueces de macadamia, pecanas, piñones, pistachos, nueces, semillas consumidas como nueces, etc.)'],
            ['cuso_catego'=>'Alimento humano',                 'cuso_uso'=>'Aceites, Gomas',                                  'cuso_describe'=>'Aceites, Gomas (aceite de oliva, aceite de canola, aceite de maíz, aceite de semilla de algodón, aceite de sésamo, otros aceites de cocina, goma arábiga, carragenina, celulosa, goma guar, goma de algarroba, pectina, etc.)'],
            ['cuso_catego'=>'Alimento humano',                 'cuso_uso'=>'Aditivos',                                        'cuso_describe'=>'Aditivos (clarificante, colorante, emulsionante, extensor/espesante, agente fermentador, conservante aromatizante, edulcorante, ablandador, vinagre, etc.)'],
            ['cuso_catego'=>'Alimento humano',                 'cuso_uso'=>'Otro (detallar en Modo en que se Usa)',           'cuso_describe'=>'Otro/NA (Al seleccionar esta subcategoría, se le pedirá que ingrese información de uso en la categoría de notas).'],
            ['cuso_catego'=>'Alimento animal',                 'cuso_uso'=>'Forraje/forraje.pastoreo.ensilaje',               'cuso_describe'=>'Forraje/forraje.pastoreo.ensilaje (heno, paja, pastos, cereales, tubérculos, col rizada y colza, etc.)'],
            ['cuso_catego'=>'Alimento animal',                 'cuso_uso'=>'Explorar',                                        'cuso_describe'=>'Explorar (brotes, hojas y ramitas de especies leñosas consumidas como alimento, etc.)'],
            ['cuso_catego'=>'Alimento animal',                 'cuso_uso'=>'Alimento de invertebrados y plantas de abejas ',  'cuso_describe'=>'Alimento de invertebrados y plantas de abejas (cualquier planta consumida por invertebrados que sea utilizada por los humanos: abejas (fuentes de polen/néctar), gusanos de seda, cochinillas, insectos colorantes, orugas, larvas y plantas de mariposas, etc.)'],
            ['cuso_catego'=>'Alimento animal',                 'cuso_uso'=>'Frutas',                                          'cuso_describe'=>'Frutas (cualquier fruta consumida por los animales como alimento)'],
            ['cuso_catego'=>'Alimento animal',                 'cuso_uso'=>'Otro/NA',                                         'cuso_describe'=>'Otro/NA (Al seleccionar esta subcategoría, se le pedirá que ingrese información de uso en la categoría de notas).'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sangre y sistema circulatorio',             'cuso_describe'=>'Sangre y sistema circulatorio (anemia, aorta, sangre, moretones, presión arterial, vasos sanguíneos, médula ósea, circulación cerebral, capilares, dolor en el pecho, gangrena, corazón, ataque cardíaco, latidos cardíacos, enfermedades cardíacas, válvulas cardíacas, hemorragias, pulmón). circulación, plasma, plaquetas, glóbulos rojos, anemia falciforme, bazo, venas, glóbulos blancos, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Dental',                                    'cuso_describe'=>'Dental (caries, encías, labios, boca, saliva, glándulas salivales, dientes, dentición, lengua, limpieza dental, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistema digestivo',                         'cuso_describe'=>'Sistema digestivo (abdomen, fisuras anales, ano, apendicitis, apéndice, conducto biliar, distensión abdominal, colitis, colon, estreñimiento, diarrea, digestión, duodeno, calvicie biliar, cálculos biliares, gases, gastroenteritis, acidez de estómago, hemorroides, hepatitis, indigestión, intestinos, síndrome del intestino irritable, laxantes, hígado, mareos, náuseas, esófago, páncreas, recto, estómago, úlceras estomacales, vómitos, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistema Endocrino',                         'cuso_describe'=>'Sistema Endocrino (Hormonas) (glándula suprarrenal, diabetes, enanismo, bocio, crecimiento, hipotálamo, células de los islotes del páncreas, paratiroides, glándula pineal, glándula pituitaria, timo, glándula tiroides, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Reproducción Femenina y Masculina',         'cuso_describe'=>'Reproducción Femenina y Masculina (aborto/aborto espontáneo, abotifaciente, afrodisíacos, anticonceptivos, senos, cuello uterino, clítoris, anticonceptivos, aocrpus luteum, óvulos, epidídimo, fertilidad, trompas de Falopio, anticoncepción femenina, prepucio, tracto genital, himen, impotencia, infertilidad, labios, parto y nacimiento, lactancia, libido, anticoncepción masculina, menopausia, menstruación, náuseas matutinas, pezones, ovarios, oviducto, ovulación, pene, placenta, síndrome premenstrual, ptregnancia, próstata, pubertad , escroto, semen, esperma, espermicida, conducto deferente, enfermedades venéreas, vagina, vulva, “enfermedades de la mujer”, etc.). '],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistema Urinario',                          'cuso_describe'=>'Sistema Urinario (vejiga, incontinencia, células renales, riñones, cálculos renales, uréter, uretra, tracto urinario, micción, orina, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistema inmunológico',                      'cuso_describe'=>'Sistema inmunológico (linfa, ganglios linfáticos, ganglios linfáticos, vasos linfáticos, linfocitos, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistema metabólico/Fiebre/Nutrición',       'cuso_describe'=>'Sistema metabólico/Fiebre/Nutrición (metabolismo de aminoácidos, antioxidantes, apetito, azúcar en sangre, regulación de la temperatura corporal, metabolismo del calcio, metabolismo de los carbohidratos, escalofríos, colesterol, deshidratación, metabolismo energético, metabolismo de las grasas, equilibrio de líquidos, electrolitos y ácidos, gota, yodo deficiencia, desnutrición, deficiencias minerales, metabolismo mineral, obesidad, sudoración, deficiencias vitamínicas, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistema musculoesquelético',                'cuso_describe'=>'Sistema musculoesquelético (tobillos, brazos, artritis, espalda, huesos, fracturas óseas, cartílagos, tórax, tejido conectivo, luxaciones, codos, cara, tejido adiposo, pies, dedos, fracturas, congelación, manos, cabeza, caderas, mandíbulas, articulación, rodillas, piernas, ligamentos, dolor muscular, espasmos musculares, calambres musculares, músculos, relajantes musculares, estimulante muscular, cuello, costillas, hombros, cráneo, músculos lisos, columna vertebral, esguince, distensión, tendones, muslos, dedos de los pies, vértebras, muñecas, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistema nervioso y salud mental',           'cuso_describe'=>'Sistema nervioso y salud mental (alcoholismo, enfermedad de Alzheimer, ansiedad, anorexia nerviosa, antidepresivos, sistema nervioso autónomo, cerebro, daño cerebral, tronco encefálico, ventrículos cerebrales, bulimia, sistema nervioso central, cerebro, coma, confusión, convulsiones, nervios craneales, delirio, delirios, demencia, depresión, mareos, drogadicción, nervios faciales, desmayos, ganglios, dolor de cabeza, locura, insomnio, salud mental, pérdida de memoria, migrañas, nervios motores, neurotransmisores, pesadillas, parasimpático sistema nervioso, sistema nervioso periférico, nervios sensoriales, sueño, médula espinal, accidente cerebrovascular, sistema nervioso simpático, temblores, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistema Respiratorio',                      'cuso_describe'=>'Sistema Respiratorio (asma, respiración, bronquiolos, congestión, tos, diafragma, enfisema, fiebre del heno, hipo, laringe, pulmones, tracto nasal, nariz, faringe, neumonía, mucosa respiratoria, dificultad para respirar, ronquidos, tórax, garganta, amígdalas, tráquea, sibilancias, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistema Sensorial',                         'cuso_describe'=>'Sistema Sensorial (ceguera, visión borrosa, cataratas, daltonismo, córneas, sordera, tímpanos, oídos, cerumen, párpados, ojos, movimientos oculares, glaucoma, audición, hipoacusia, pupilas, retinas, olfato, gusto, lágrimas, tacto, visión, etc).'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Piel y tejidos relacionados',               'cuso_describe'=>'Piel y tejidos relacionados (acné, barba, ampollas, forúnculos, hematomas, quemaduras, callosidades, dermatitis, caspa, eccema, cejas, pelaje, cabello, folículos pilosos, caída del cabello, urticaria, pezuñas, picazón, uñas, erupciones cutáneas, cuero cabelludo, piel , llagas, quemaduras solares, protector solar, glándulas sudoríparas, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Infecciones, parásitos, hongos',            'cuso_describe'=>'Infecciones, parásitos, hongos (SIDA, antibacterianos, antifúngicos, antimicrobianos, antisépticos, antivirales, infecciones bacterianas, varicela, resfriados, herpes labial, desinfectantes, disentería, pulgas, trematodos, intoxicaciones alimentarias, infecciones por hongos, anquilostomas, influenza, piojos, malaria , rabia, tiña, sarna, tenia, infecciones virales, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Venenos/antídotos, alérgenos',              'cuso_describe'=>'Venenos/antídotos, alérgenos (alérgenos (como la hiedra venenosa), antídotos para picaduras y picaduras de insectos; y cualquier cosa que cause la muerte, efectos mutagénicos, teratogénicos, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Medicina veterinaria y zoofarmacognosia',   'cuso_describe'=>'Medicina veterinaria y zoofarmacognosia (plantas utilizadas para tratar animales y plantas que los animales se autoadministran como medicina, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistemas medicinales no occidentales',      'cuso_describe'=>'Sistemas medicinales no occidentales (“humores”, calentar y enfriar el cuerpo, esencias corporales, frío, humedad, calor, viento, etc.'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Sistemas de Creencias',                     'cuso_describe'=>'Sistemas de Creencias (embrujos, mal de ojo, enfermedades sagradas, hechizos, susto, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Síntomas generales, inespecíficos',         'cuso_describe'=>'Síntomas generales, inespecíficos (incluye “tónicos” y “curadores de heridas” (tanto heridas internas como externas), reacciones alérgicas generalizadas, síntomas generales.y anestésicos locales, analgésicos generales y analgésicos, medicamentos contra la fatiga, mareos y desmayos, malestar general, dolores (incluidos dolores de cabeza) de origen no especificado, fiebres, hinchazón, debilidad, etc.)'],
            ['cuso_catego'=>'Medicina humana y veterinaria',   'cuso_uso'=>'Otro/NA',                                   'cuso_describe'=>'Otro/NA (Al seleccionar esta subcategoría, se le pedirá que ingrese información de uso en la categoría de notas).'],
            ['cuso_catego'=>'Productos químicos',              'cuso_uso'=>'Látex, caucho',                                        'cuso_describe'=>'Látex, caucho (látex de chicle, gutapercha, etc.)'],
            ['cuso_catego'=>'Productos químicos',              'cuso_uso'=>'Resinas, gomas no comestibles',                        'cuso_describe'=>'Reisinas, gomas no comestibles (mucílagos, trementina, colofonia, pectina, creosota de madera, ámbar, goma esterculia, goma ghatti, kino gu, etc.)'],
            ['cuso_catego'=>'Productos químicos',              'cuso_uso'=>'Aceites (no comestibles), ceras, jabones',             'cuso_describe'=>'Aceites (no comestibles), ceras, jabones (aceites esenciales, aceite de tung, aceite de oiticica, tall oil, hidrogeles, cera de carnauba, cera de candelilla, cera de jojoba, cera de caña de azúcar, arándano, saponinas, etc.)'],
            ['cuso_catego'=>'Productos químicos',              'cuso_uso'=>'Tintes, pinturas',                                     'cuso_describe'=>'Tintes, pinturas (aceite de linaza, tinta a base de soja, resina de damar, henna, azul índigo, achiote, raíz de rubia, espuela de caballero, etc.)'],
            ['cuso_catego'=>'Productos químicos',              'cuso_uso'=>'Taninos, flavonoides, otros polifenoles',              'cuso_describe'=>'Taninos, flavonoides, otros polifenoles (Taninos, antocianos, flavonoles, glucósidos, isoflavonas, etc.)'],
            ['cuso_catego'=>'Productos químicos',              'cuso_uso'=>'Aromáticos/perfumes',                                  'cuso_describe'=>'Aromáticos/perfumes (incienso, mirra, incienso (uso no religioso), perfume, etc.)'],
            ['cuso_catego'=>'Productos químicos',              'cuso_uso'=>'Disolventes',                                          'cuso_describe'=>'Disolventes (alcoholes de madera, derivados del tall oil, etc.)'],
            ['cuso_catego'=>'Productos químicos',              'cuso_uso'=>'Adhesivos',                                            'cuso_describe'=>'Adhesivos (derivados del Tall Oil, goma arábiga, goma tragacanto, etc.)'],
            ['cuso_catego'=>'Productos químicos',              'cuso_uso'=>'Otro/NA',                                              'cuso_describe'=>'Otro/NA (Al seleccionar esta subcategoría, se le pedirá que ingrese información de uso en la categoría de notas).'],
            ['cuso_catego'=>'Combustible',                      'cuso_uso'=>'Leña, carbón vegetal',                                'cuso_describe'=>'Leña, carbón vegetal (leños, leña, hojas, raíces, carbón vegetal, etc.)'],
            ['cuso_catego'=>'Combustible',                      'cuso_uso'=>'Aceite, alcohol, resinas, ceras',                     'cuso_describe'=>'Aceite, alcohol, resinas, ceras (aceites no comestibles, alcoholes de madera, savias, etc.)'],
            ['cuso_catego'=>'Combustible',                      'cuso_uso'=>'Iniciadores de fuego',                                 'cuso_describe'=>'Iniciadores de fuego (cualquier cosa utilizada específicamente para iniciar incendios: yesca, etc.)'],
            ['cuso_catego'=>'Combustible',                      'cuso_uso'=>'Otro/NA',                                              'cuso_describe'=>'Otro/NA (Al seleccionar esta subcategoría, se le pedirá que ingrese información de uso en la categoría de notas).'],
            ['cuso_catego'=>'Fibras',                           'cuso_uso'=>'Telas, hilos, prendas de vestir, prendas de vestir',   'cuso_describe'=>'Telas, hilos, prendas de vestir, prendas de vestir (Telas, arpilleras, vestidos, sombreros, cascos, sandalias, bufandas, zapatos, pantuflas, impermeables, etc.)'],
            ['cuso_catego'=>'Fibras',                           'cuso_uso'=>'Papel',                                                'cuso_describe'=>'Papel (papel, sucedáneos del papel, cartón, etc.)'],
            ['cuso_catego'=>'Fibras',                           'cuso_uso'=>'Cestas/contenedores de vibro/artículos de hogar de fibra/artesanías de fibra',             'cuso_describe'=>'Cestas/contenedores de vibro/artículos de hogar de fibra/artesanías de fibra (cestería, bolsos, mantas, alfombras/tapetes, cortinas, cojines, almohadas, tapices, manteles individuales, posavasos, hamacas, colchones, etc.)'],
            ['cuso_catego'=>'Fibras',                           'cuso_uso'=>'Cuerda/red/cordel',                                    'cuso_describe'=>'Cuerda/red/cordel (cuerda, cordón, cordel, hilo, etc.)'],
            ['cuso_catego'=>'Fibras',                           'cuso_uso'=>'Otro/NA',                                              'cuso_describe'=>'Otro/NA (Al seleccionar esta subcategoría, se le pedirá que ingrese información de uso en la categoría de notas).'],
            ['cuso_catego'=>'Usos culturales',                  'cuso_uso'=>'Artesanías (sin fibra)',                               'cuso_describe'=>'Artesanías (sin fibra) (tallas de madera, platos, cuencos, marcos de cuadros, cerámica, coronas, etc.)'],
            ['cuso_catego'=>'Usos culturales',                  'cuso_uso'=>'Recreativos/juegos/deportes/juguetes',                 'cuso_describe'=>'Recreativos/juegos/deportes/juguetes (equipo de pesca, equipo de caza, pelotas, bates deportivos, raquetas y palos, esquís y raquetas de nieve, juegos de mesa, dados, muñecos, rompecabezas, etc.)'],
            ['cuso_catego'=>'Usos culturales',                  'cuso_uso'=>'Religiosos',                                           'cuso_describe'=>'Religiosos (plantas rituales (incluido incienso religioso), plantas sagradas, magia/misticismo, rosarios, etc.)'],
            ['cuso_catego'=>'Usos culturales',                  'cuso_uso'=>'Accesorios, joyería, cosméticos',                      'cuso_describe'=>'Accesorios, joyería, cosméticos (cuentas, cinturones, aceite para el cabello, tintes para el cabello, acondicionadores para el cabello, lociones/cremas para la piel, aclaradores/oscurecedores de la piel, tatuajes, lápices labiales, pinturas corporales, desodorantes corporales, peines y cepillos para el cabello, pulseras, aretes, collares, equipos de afeitado, limpiadores de dientes, etc.)'],
            ['cuso_catego'=>'Usos culturales',                  'cuso_uso'=>'Instrumentos musicales, arte',                         'cuso_describe'=>'Instrumentos musicales, arte (flautas, flautas, tambores, laúdes, guitarras, violines, arpas, esculturas, móviles, tótems, etc.)'],
            ['cuso_catego'=>'Usos culturales',                  'cuso_uso'=>'Drogas psicoactivas',                                  'cuso_describe'=>'Drogas psicoactivas (hongos alucinógenos, estupefacientes, estupefacientes, tabaco, materiales para fumar, etc.)'],
            ['cuso_catego'=>'Usos culturales',                  'cuso_uso'=>'Otro/NA',                                              'cuso_describe'=>'Otro/NA (Al seleccionar esta subcategoría, se le pedirá que ingrese información de uso en la categoría de notas).'],
            ['cuso_catego'=>'Construcción o material estructural','cuso_uso'=>'Madera',                                             'cuso_describe'=>'Madera (vigas, columnas, tablones, postes de madera, estacas, tablas de madera, astillas de madera, etc.)'],
            ['cuso_catego'=>'Construcción o material estructural','cuso_uso'=>'Mobiliario',                                         'cuso_describe'=>'Mobiliario (camas, somieres, armarios, sillas, sofás, taburetes, mesas, armarios, etc.)'],
            ['cuso_catego'=>'Construcción o material estructural','cuso_uso'=>'Material de construcción',                           'cuso_describe'=>'Material de construcción (suelos de palma, parquet, paja, enredaderas para atar vigas, etc.)'],
            ['cuso_catego'=>'Construcción o material estructural','cuso_uso'=>'Herramientas, utensilios',                           'cuso_describe'=>'Herramientas, utensilios (artículos domésticos que no sean de fibra, herramientas agrícolas, bobinas, carretes, herramientas de carpintería, morteros, ralladores, martillos, mazos, escaleras, agujas, rastrillos, palas, mangos de herramientas, palillos, tenedores, cuchillos, cucharas, espátulas , batidores, armas, etc.)'],
            ['cuso_catego'=>'Construcción o material estructural','cuso_uso'=>'Transporte',                                         'cuso_describe'=>'Transporte (botes, canoas, remos, palas, carros, planeadores, balsas, remolques, carretas, ruedas, etc.)'],
            ['cuso_catego'=>'Construcción o material estructural','cuso_uso'=>'Otro/NA',                                            'cuso_describe'=>'Otro/NA (Al seleccionar esta subcategoría, se le pedirá que ingrese información de uso en la categoría de notas).'],
            ['cuso_catego'=>'Medio ambiente',   'cuso_uso'=>'Barreras/límites',                                                     'cuso_describe'=>'Barreras/límites (cortafuegos, cercas vivas, estacas vivas, setos, líneas de árboles, sombra/refugio, etc.)'],
            ['cuso_catego'=>'Medio ambiente',   'cuso_uso'=>'Control de erosión',                                                   'cuso_describe'=>'Control de erosión (coberturas de suelo, revegetación, cortavientos, retención de agua, etc.)'],
            ['cuso_catego'=>'Medio ambiente',   'cuso_uso'=>'Fertilizantes, mejora de suelos',                                      'cuso_describe'=>'Fertilizantes, mejora de suelos (mulches, fijadores de nitrógeno, mejora de la estructura del suelo, mejora de la calidad del suelo, etc.)'],
            ['cuso_catego'=>'Medio ambiente',   'cuso_uso'=>'Plantas ornamentales',                                                 'cuso_describe'=>'Plantas ornamentales (floricultura, horticultura paisajística, paisajismo, césped, jardines privados, jardines botánicos, parques, céspedes deportivos, etc.)'],
            ['cuso_catego'=>'Medio ambiente',   'cuso_uso'=>'Control de la Contaminación',                                          'cuso_describe'=>'Control de la Contaminación (purificadores de aguas residuales, reductores de la contaminación del aire, tratamiento de aguas residuales, etc.)'],
            ['cuso_catego'=>'Medio ambiente',   'cuso_uso'=>'Control de plagas y malezas',                                          'cuso_describe'=>'Control de plagas y malezas (repelente de insectos, insecticida, control de malezas (herbicida), control de enfermedades de las plantas, control de plagas de plantas, control de plagas, control de plagas domésticas, protección de la madera, control de vectores de enfermedades humanas o animales, etc.)'],
            ['cuso_catego'=>'Medio ambiente',   'cuso_uso'=>'Otro/NA',                                                              'cuso_describe'=>'Otro/NA (Al seleccionar esta subcategoría, se le pedirá que ingrese información de uso en la categoría de notas).'],
            ['cuso_catego'=>'Otro',   'cuso_uso'=>'Investigación',                                                                  'cuso_describe'=>'Investigación (plantas utilizadas en o como objeto de cualquier tipo de investigación)'],
            ['cuso_catego'=>'Otro',   'cuso_uso'=>'Recursos genéticos',                                                             'cuso_describe'=>'Recursos genéticos (parientes silvestres de cultivos importantes que tienen cualidades como resistencia a enfermedades, tolerancia al frío, resistencia a la sequía, alto rendimiento, etc., que podrían ser valiosos en programas de mejoramiento)'],
            ['cuso_catego'=>'Otro',   'cuso_uso'=>'Agrosilvicultura',                                                               'cuso_describe'=>'Agrosilvicultura (cultivos en callejones (cultivos que crecen entre hileras de árboles), cultivos intercalados, cultivos en viveros, plantas repelentes de insectos, cultivadas en campos de cultivo, etc. Al seleccionar esta subcategoría, también debe ingresar el uso del cultivo (por ejemplo, comestible, madera, etc.))'],
            ['cuso_catego'=>'Otro',   'cuso_uso'=>'Otro',                                                                           'cuso_describe'=>'Otro (al seleccionar esta subcategoría, se le pedirá que ingrese información de uso en la categoría de notas).']
        ];

        if(cat_usos::count() == 0 ) {
            foreach ($events as $event){
                cat_usos::create($event);
            }
        }
    }
}


